sample_users = [
    {
        "id": "1", 
        "name": "John Doe", 
        "email": "john@example.com", 
        "created_at": "2024-01-15T10:30:00",
        "role": "admin",
        "avatar": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face",
        "bio": "Real estate professional with 10+ years of experience in luxury properties.",
        "location": "New York, NY",
        "phone": "+1 (555) 123-4567"
    },
    {
        "id": "2", 
        "name": "Jane Smith", 
        "email": "jane@example.com", 
        "created_at": "2024-01-16T14:20:00",
        "role": "premium",
        "avatar": "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face",
        "bio": "Interior designer and property enthusiast. Love transforming spaces into dream homes.",
        "location": "Los Angeles, CA",
        "phone": "+1 (555) 234-5678"
    },
    {
        "id": "3", 
        "name": "Bob Johnson", 
        "email": "bob@example.com", 
        "created_at": "2024-01-17T09:15:00",
        "role": "user",
        "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
        "bio": "First-time home buyer sharing my journey and learning about real estate investment.",
        "location": "Chicago, IL",
        "phone": "+1 (555) 345-6789"
    },
    {
        "id": "4", 
        "name": "Alice Brown", 
        "email": "alice@example.com", 
        "created_at": "2024-01-18T11:45:00",
        "role": "premium",
        "avatar": "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=face",
        "bio": "Real estate investor focused on commercial properties and urban development projects.",
        "location": "Miami, FL",
        "phone": "+1 (555) 456-7890"
    },
    {
        "id": "5", 
        "name": "Mike Wilson", 
        "email": "mike@example.com", 
        "created_at": "2024-01-19T13:20:00",
        "role": "user",
        "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face",
        "bio": "Tech professional passionate about smart homes and sustainable living solutions.",
        "location": "Seattle, WA",
        "phone": "+1 (555) 567-8901"
    },
    {
        "id": "6", 
        "name": "Sarah Davis", 
        "email": "sarah@example.com", 
        "created_at": "2024-01-20T08:15:00",
        "role": "admin",
        "avatar": "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=400&fit=crop&crop=face",
        "bio": "Real estate agent specializing in waterfront properties and luxury estates.",
        "location": "San Diego, CA",
        "phone": "+1 (555) 678-9012"
    },
    {
        "id": "7", 
        "name": "David Lee", 
        "email": "david@example.com", 
        "created_at": "2024-01-21T16:30:00",
        "role": "user",
        "avatar": "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=400&h=400&fit=crop&crop=face",
        "bio": "Architect and property developer with a focus on modern sustainable design.",
        "location": "Austin, TX",
        "phone": "+1 (555) 789-0123"
    },
    {
        "id": "8", 
        "name": "Emily Clark", 
        "email": "emily@example.com", 
        "created_at": "2024-01-22T12:00:00",
        "role": "premium",
        "avatar": "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=400&fit=crop&crop=face",
        "bio": "Lifestyle blogger sharing home organization tips and DIY renovation projects.",
        "location": "Portland, OR",
        "phone": "+1 (555) 890-1234"
    },
    {
        "id": "9", 
        "name": "Chris Taylor", 
        "email": "chris@example.com", 
        "created_at": "2024-01-23T14:45:00",
        "role": "user",
        "avatar": "https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?w=400&h=400&fit=crop&crop=face",
        "bio": "Real estate photographer capturing the beauty of homes across the country.",
        "location": "Denver, CO",
        "phone": "+1 (555) 901-2345"
    },
    {
        "id": "10", 
        "name": "Lisa Anderson", 
        "email": "lisa@example.com", 
        "created_at": "2024-01-24T09:30:00",
        "role": "premium",
        "avatar": "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=400&fit=crop&crop=face",
        "bio": "Property manager with expertise in vacation rentals and hospitality services.",
        "location": "Nashville, TN",
        "phone": "+1 (555) 012-3456"
    }
]
sample_posts = [
    {
        "id": "1", 
        "title": "My First Home Purchase Journey", 
        "content": "After years of saving and searching, I finally found my dream home! The process was challenging but incredibly rewarding. From mortgage pre-approval to closing day, every step taught me valuable lessons about the real estate market.",
        "author": "1", 
        "created_at": "2024-01-18T10:00:00",
        "image": "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=600&h=400&fit=crop",
        "category": "Personal Experience",
        "likes": 24,
        "comments": 8
    },
    {
        "id": "2", 
        "title": "Renovating a Historic Townhouse", 
        "content": "We took on a 1920s townhouse that needed complete restoration. Preserving the original character while adding modern amenities was our biggest challenge. The hardwood floors, crown molding, and stained glass windows were worth every moment of effort!",
        "author": "2", 
        "created_at": "2024-01-18T11:30:00",
        "image": "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=600&h=400&fit=crop",
        "category": "Renovation",
        "likes": 42,
        "comments": 15
    },
    {
        "id": "3", 
        "title": "Smart Home Automation Guide", 
        "content": "Transformed my entire house with smart technology! From voice-controlled lighting to security systems that I can monitor from anywhere. Here's my complete setup and the best devices for different budgets and needs.",
        "author": "1", 
        "created_at": "2024-01-18T12:45:00",
        "image": "https://images.unsplash.com/photo-1558002038-105589864b83?w=600&h=400&fit=crop",
        "category": "Technology",
        "likes": 31,
        "comments": 12
    },
    {
        "id": "4", 
        "title": "Seasonal Home Maintenance Checklist", 
        "content": "Spring is the perfect time for home maintenance! My comprehensive checklist covers everything from gutter cleaning to HVAC system checks. Don't forget to inspect your roof and clean those hard-to-reach windows.",
        "author": "3", 
        "created_at": "2024-01-19T14:20:00",
        "image": "https://images.unsplash.com/photo-1581578021546-cc88d9e71887?w=600&h=400&fit=crop",
        "category": "Maintenance",
        "likes": 56,
        "comments": 9
    },
    {
        "id": "5", 
        "title": "Creating the Perfect Home Office", 
        "content": "With remote work becoming the norm, I designed the ultimate home office space. Ergonomic furniture, proper lighting, and soundproofing made all the difference. Productivity has never been higher!",
        "author": "4", 
        "created_at": "2024-01-20T09:15:00",
        "image": "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=400&fit=crop",
        "category": "Interior Design",
        "likes": 38,
        "comments": 14
    },
    {
        "id": "6", 
        "title": "Urban Gardening on a Balcony", 
        "content": "You don't need a backyard to grow your own food! My small balcony now produces herbs, vegetables, and flowers year-round. Vertical gardening and container solutions maximize limited space beautifully.",
        "author": "2", 
        "created_at": "2024-01-21T16:45:00",
        "image": "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=400&fit=crop",
        "category": "Gardening",
        "likes": 67,
        "comments": 23
    },
    {
        "id": "7", 
        "title": "Energy Efficiency Upgrades That Pay Off", 
        "content": "Reduced my energy bills by 40% with these smart upgrades! Solar panels, smart thermostats, and proper insulation not only save money but also increase property value. The ROI calculations might surprise you.",
        "author": "5", 
        "created_at": "2024-01-22T11:30:00",
        "image": "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600&h=400&fit=crop",
        "category": "Sustainability",
        "likes": 89,
        "comments": 31
    },
    {
        "id": "8", 
        "title": "Vintage Furniture Restoration Tips", 
        "content": "Found this beautiful mid-century modern dresser at a flea market and brought it back to life! Sharing my step-by-step process for cleaning, repairing, and refinishing vintage furniture pieces.",
        "author": "6", 
        "created_at": "2024-01-23T13:20:00",
        "image": "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=400&fit=crop",
        "category": "DIY",
        "likes": 45,
        "comments": 18
    },
    {
        "id": "9", 
        "title": "Coastal Interior Design Inspiration", 
        "content": "Bringing the beach vibe indoors with light colors, natural textures, and nautical accents. My home now feels like a permanent vacation with these coastal design principles and affordable decor finds.",
        "author": "7", 
        "created_at": "2024-01-24T10:15:00",
        "image": "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&h=400&fit=crop",
        "category": "Interior Design",
        "likes": 52,
        "comments": 21
    },
    {
        "id": "10", 
        "title": "Home Security System Comparison", 
        "content": "Tested 5 popular home security systems over 6 months. From DIY setups to professional monitoring, here's my honest review of features, pricing, and reliability to help you choose the right protection.",
        "author": "8", 
        "created_at": "2024-01-25T15:40:00",
        "image": "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&h=400&fit=crop",
        "category": "Security",
        "likes": 73,
        "comments": 27
    },
    {
        "id": "11", 
        "title": "Tiny House Living: 1 Year Review", 
        "content": "After 12 months in my 350 sq ft tiny home, I'm sharing the surprising pros and cons. The freedom is incredible, but there are challenges too. Would I do it again? Absolutely!",
        "author": "9", 
        "created_at": "2024-01-26T12:30:00",
        "image": "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=600&h=400&fit=crop",
        "category": "Lifestyle",
        "likes": 128,
        "comments": 45
    },
    {
        "id": "12", 
        "title": "Backyard Oasis on a Budget", 
        "content": "Transformed my boring backyard into a relaxing retreat for under $2,000! DIY fire pit, string lights, and container gardening created the perfect space for entertaining and unwinding.",
        "author": "10", 
        "created_at": "2024-01-27T14:15:00",
        "image": "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&h=400&fit=crop",
        "category": "Outdoor",
        "likes": 94,
        "comments": 33
    },
    {
        "id": "13", 
        "title": "Minimalist Kitchen Makeover", 
        "content": "Decluttered and redesigned my kitchen using minimalist principles. The result: more counter space, easier cleaning, and a peaceful cooking environment. Less really is more!",
        "author": "3", 
        "created_at": "2024-01-28T16:45:00",
        "image": "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&h=400&fit=crop",
        "category": "Minimalism",
        "likes": 61,
        "comments": 19
    },
    {
        "id": "14", 
        "title": "Home Theater Setup Guide", 
        "content": "Created the ultimate movie night experience at home! From projector selection to acoustic treatment, here's everything you need to know about building your own cinema paradise.",
        "author": "4", 
        "created_at": "2024-01-29T11:20:00",
        "image": "https://images.unsplash.com/photo-1581833971358-2c8b550f87b3?w=600&h=400&fit=crop",
        "category": "Entertainment",
        "likes": 47,
        "comments": 16
    },
    {
        "id": "15", 
        "title": "First-Time Landlord Lessons", 
        "content": "After renting out my first property for a year, I've learned so much about tenant screening, maintenance schedules, and legal requirements. Sharing my mistakes and successes for aspiring landlords!",
        "author": "5", 
        "created_at": "2024-01-30T13:50:00",
        "image": "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=600&h=400&fit=crop",
        "category": "Investment",
        "likes": 82,
        "comments": 29
    }
]

sample_properties= [
        {
            "id": "1",
            "title": "Luxury Beachfront Villa",
            "description": "Stunning 4-bedroom villa with private beach access and panoramic ocean views. Features modern amenities and spacious living areas.",
            "price": 2500000,
            "location": "Malibu, California",
            "bedrooms": 4,
            "bathrooms": 3,
            "square_feet": 3200,
            "property_type": "Villa",
            "year_built": 2018,
            "owner_id": "1",
            "created_at": "2024-01-15T09:00:00",
            "image": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&h=400&fit=crop"
        },
        {
            "id": "2",
            "title": "Downtown Modern Loft",
            "description": "Beautiful industrial-style loft in the heart of downtown. High ceilings, exposed brick, and modern finishes throughout.",
            "price": 850000,
            "location": "New York, NY",
            "bedrooms": 2,
            "bathrooms": 2,
            "square_feet": 1800,
            "property_type": "Loft",
            "year_built": 2020,
            "owner_id": "2",
            "created_at": "2024-01-16T14:30:00",
            "image": "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&h=400&fit=crop"
        },
        {
            "id": "3",
            "title": "Mountain Retreat Cabin",
            "description": "Cozy log cabin nestled in the mountains. Perfect for nature lovers with hiking trails and stunning views.",
            "price": 450000,
            "location": "Aspen, Colorado",
            "bedrooms": 3,
            "bathrooms": 2,
            "square_feet": 2200,
            "property_type": "Cabin",
            "year_built": 2015,
            "owner_id": "3",
            "created_at": "2024-01-17T11:20:00",
            "image": "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=600&h=400&fit=crop"
        },
        {
            "id": "4",
            "title": "Suburban Family Home",
            "description": "Spacious family home in quiet neighborhood. Large backyard, updated kitchen, and excellent school district.",
            "price": 675000,
            "location": "Austin, Texas",
            "bedrooms": 5,
            "bathrooms": 3,
            "square_feet": 2800,
            "property_type": "Single Family",
            "year_built": 2012,
            "owner_id": "4",
            "created_at": "2024-01-18T10:15:00",
            "image": "https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=600&h=400&fit=crop"
        },
        {
            "id": "5",
            "title": "Urban Penthouse Suite",
            "description": "Luxurious penthouse with rooftop terrace and city skyline views. High-end finishes and premium amenities.",
            "price": 3200000,
            "location": "Miami, Florida",
            "bedrooms": 3,
            "bathrooms": 3,
            "square_feet": 3500,
            "property_type": "Penthouse",
            "year_built": 2022,
            "owner_id": "5",
            "created_at": "2024-01-19T16:45:00",
            "image": "https://images.unsplash.com/photo-1513584684374-8bab748fbf90?w=600&h=400&fit=crop"
        },
        {
            "id": "6",
            "title": "Historic Townhouse",
            "description": "Beautifully restored historic townhouse with original features and modern updates. Located in charming historic district.",
            "price": 1200000,
            "location": "Charleston, South Carolina",
            "bedrooms": 4,
            "bathrooms": 3,
            "square_feet": 2600,
            "property_type": "Townhouse",
            "year_built": 1890,
            "owner_id": "6",
            "created_at": "2024-01-20T13:30:00",
            "image": "https://images.unsplash.com/photo-1513584684374-8bab748fbf90?w=600&h=400&fit=crop"
        },
        {
            "id": "7",
            "title": "Lakefront Cottage",
            "description": "Charming cottage on pristine lake. Private dock, fishing access, and peaceful surroundings perfect for relaxation.",
            "price": 550000,
            "location": "Lake Tahoe, California",
            "bedrooms": 2,
            "bathrooms": 1,
            "square_feet": 1500,
            "property_type": "Cottage",
            "year_built": 2008,
            "owner_id": "7",
            "created_at": "2024-01-21T09:45:00",
            "image": "https://images.unsplash.com/photo-1475855581690-80accde3ae2b?w=600&h=400&fit=crop"
        },
        {
            "id": "8",
            "title": "Modern Condo",
            "description": "Sleek contemporary condo with smart home features and resort-style amenities including pool and gym.",
            "price": 725000,
            "location": "Seattle, Washington",
            "bedrooms": 2,
            "bathrooms": 2,
            "square_feet": 1400,
            "property_type": "Condo",
            "year_built": 2019,
            "owner_id": "8",
            "created_at": "2024-01-22T15:20:00",
            "image": "https://images.unsplash.com/photo-1540518614846-7eded1027f2b?w=600&h=400&fit=crop"
        },
        {
            "id": "9",
            "title": "Ranch Style Estate",
            "description": "Expansive single-story ranch on 5 acres. Horse barn, pool, and mature landscaping throughout the property.",
            "price": 1850000,
            "location": "Nashville, Tennessee",
            "bedrooms": 4,
            "bathrooms": 4,
            "square_feet": 4200,
            "property_type": "Ranch",
            "year_built": 2016,
            "owner_id": "9",
            "created_at": "2024-01-23T11:10:00",
            "image": "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=600&h=400&fit=crop"
        },
        {
            "id": "10",
            "title": "Ski-in/Ski-out Chalet",
            "description": "Luxury ski chalet with direct slope access. Hot tub, fireplace, and mountain views from every room.",
            "price": 2900000,
            "location": "Park City, Utah",
            "bedrooms": 5,
            "bathrooms": 4,
            "square_feet": 3800,
            "property_type": "Chalet",
            "year_built": 2014,
            "owner_id": "10",
            "created_at": "2024-01-24T14:50:00",
            "image": "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&h=400&fit=crop"
        },
        {
            "id": "11",
            "title": "Waterfront Modern Home",
            "description": "Architectural masterpiece with floor-to-ceiling windows overlooking the water. Infinity pool and private beach.",
            "price": 4200000,
            "location": "San Diego, California",
            "bedrooms": 4,
            "bathrooms": 4,
            "square_feet": 4500,
            "property_type": "Modern",
            "year_built": 2021,
            "owner_id": "1",
            "created_at": "2024-01-25T10:30:00",
            "image": "https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=600&h=400&fit=crop"
        },
        {
            "id": "12",
            "title": "City View Apartment",
            "description": "Sophisticated apartment with stunning city views. Walking distance to restaurants, shops, and entertainment.",
            "price": 950000,
            "location": "Chicago, Illinois",
            "bedrooms": 2,
            "bathrooms": 2,
            "square_feet": 1600,
            "property_type": "Apartment",
            "year_built": 2017,
            "owner_id": "2",
            "created_at": "2024-01-26T12:15:00",
            "image": "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&h=400&fit=crop"
        },
        {
            "id": "13",
            "title": "Country Farmhouse",
            "description": "Renovated farmhouse with original charm and modern comforts. Large porch, barn, and rolling hills.",
            "price": 890000,
            "location": "Lancaster, Pennsylvania",
            "bedrooms": 3,
            "bathrooms": 2,
            "square_feet": 2400,
            "property_type": "Farmhouse",
            "year_built": 1930,
            "owner_id": "3",
            "created_at": "2024-01-27T08:45:00",
            "image": "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=600&h=400&fit=crop"
        },
        {
            "id": "14",
            "title": "Desert Oasis",
            "description": "Minimalist desert home with private courtyard and mountain views. Sustainable design and solar powered.",
            "price": 1250000,
            "location": "Scottsdale, Arizona",
            "bedrooms": 3,
            "bathrooms": 2,
            "square_feet": 2200,
            "property_type": "Modern",
            "year_built": 2020,
            "owner_id": "4",
            "created_at": "2024-01-28T17:30:00",
            "image": "https://images.unsplash.com/photo-1516455590571-18256e5bb9ff?w=600&h=400&fit=crop"
        },
        {
            "id": "15",
            "title": "Victorian Mansion",
            "description": "Grand Victorian mansion with period details and modern updates. Wraparound porch and carriage house.",
            "price": 2750000,
            "location": "San Francisco, California",
            "bedrooms": 6,
            "bathrooms": 4,
            "square_feet": 5200,
            "property_type": "Victorian",
            "year_built": 1901,
            "owner_id": "5",
            "created_at": "2024-01-29T14:20:00",
            "image": "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=600&h=400&fit=crop"
        },
        
    {
        "id": "16",
        "title": "Upscale Downtown Condo",
        "description": "Elegant condo in the financial district with concierge service, gym, and stunning skyline views. Perfect for urban professionals.",
        "price": 1100000,
        "location": "Boston, Massachusetts",
        "bedrooms": 2,
        "bathrooms": 2,
        "square_feet": 1650,
        "property_type": "Condo",
        "year_built": 2018,
        "owner_id": "6",
        "created_at": "2024-01-30T10:00:00",
        "image": "https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=600&h=400&fit=crop"
    },
    {
        "id": "17",
        "title": "Minimalist Modern Residence",
        "description": "Clean lines and open spaces define this architectural gem. Features smart home integration and a zen garden.",
        "price": 1850000,
        "location": "Portland, Oregon",
        "bedrooms": 3,
        "bathrooms": 3,
        "square_feet": 2700,
        "property_type": "Modern",
        "year_built": 2022,
        "owner_id": "7",
        "created_at": "2024-01-31T13:15:00",
        "image": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&h=400&fit=crop"
    },
    {
        "id": "18",
        "title": "Spacious Suburban Family Home",
        "description": "Move-in ready home in a top-rated school zone. Features a finished basement, large deck, and two-car garage.",
        "price": 720000,
        "location": "Denver, Colorado",
        "bedrooms": 4,
        "bathrooms": 3,
        "square_feet": 3100,
        "property_type": "Single Family",
        "year_built": 2015,
        "owner_id": "8",
        "created_at": "2024-02-01T11:45:00",
        "image": "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=600&h=400&fit=crop"
    },
    {
        "id": "19",
        "title": "Harbor View Condo",
        "description": "Bright corner unit with panoramic harbor views. Walking distance to marinas, shops, and fine dining.",
        "price": 950000,
        "location": "Annapolis, Maryland",
        "bedrooms": 1,
        "bathrooms": 2,
        "square_feet": 1350,
        "property_type": "Condo",
        "year_built": 2016,
        "owner_id": "9",
        "created_at": "2024-02-02T15:30:00",
        "image": "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&h=400&fit=crop"
    },
    {
        "id": "20",
        "title": "Desert Modern Oasis",
        "description": "This home blends seamlessly with its natural surroundings. Features floor-to-ceiling windows, a saltwater pool, and an outdoor kitchen.",
        "price": 2100000,
        "location": "Palm Springs, California",
        "bedrooms": 4,
        "bathrooms": 4,
        "square_feet": 3400,
        "property_type": "Modern",
        "year_built": 2020,
        "owner_id": "10",
        "created_at": "2024-02-03T09:20:00",
        "image": "https://images.unsplash.com/photo-1516455590571-18256e5bb9ff?w=600&h=400&fit=crop"
    },
    {
        "id": "21",
        "title": "Classic American Family Home",
        "description": "A perfect home for entertaining with an open floor plan, updated chef's kitchen, and a large, fenced backyard.",
        "price": 650000,
        "location": "Charlotte, North Carolina",
        "bedrooms": 5,
        "bathrooms": 3,
        "square_feet": 2900,
        "property_type": "Single Family",
        "year_built": 2011,
        "owner_id": "1",
        "created_at": "2024-02-04T14:10:00",
        "image": "https://images.unsplash.com/photo-1513584684374-8bab748fbf90?w=600&h=400&fit=crop"
    },
    {
        "id": "22",
        "title": "Lakeside Condo Retreat",
        "description": "Peaceful condo on a serene lake. Enjoy morning coffee on the balcony overlooking the water. Includes secure underground parking.",
        "price": 575000,
        "location": "Madison, Wisconsin",
        "bedrooms": 2,
        "bathrooms": 2,
        "square_feet": 1500,
        "property_type": "Condo",
        "year_built": 2014,
        "owner_id": "2",
        "created_at": "2024-02-05T16:40:00",
        "image": "https://images.unsplash.com/photo-1475855581690-80accde3ae2b?w=600&h=400&fit=crop"
    },
    {
        "id": "23",
        "title": "Updated Single Family Home",
        "description": "Completely renovated from top to bottom. New roof, HVAC, kitchen, and bathrooms. A turn-key property in a desirable community.",
        "price": 830000,
        "location": "Atlanta, Georgia",
        "bedrooms": 4,
        "bathrooms": 3,
        "square_feet": 2600,
        "property_type": "Single Family",
        "year_built": 1995,
        "owner_id": "3",
        "created_at": "2024-02-06T12:25:00",
        "image": "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=600&h=400&fit=crop"
    }
]
    